apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-wordpress
spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: {{ .Release.Name }}-wordpress

  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-wordpress

    spec:
      containers:
      - name: wordpress
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}

        env:
        - name: WORDPRESS_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-wordpress-config
              key: WORDPRESS_DB_HOST

        - name: WORDPRESS_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-wordpress-config
              key: WORDPRESS_DB_NAME

        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-mysql-secret
              key: WORDPRESS_DB_USER

        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-mysql-secret
              key: WORDPRESS_DB_PASSWORD

        ports:
        - containerPort: 80

        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu | quote }}
            memory: {{ .Values.resources.requests.memory | quote }}
          limits:
            cpu: {{ .Values.resources.limits.cpu | quote }}
            memory: {{ .Values.resources.limits.memory | quote }}
