apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-mysql

spec:
  replicas: {{ .Values.mysql.replicas }}

  serviceName: {{ .Release.Name }}-mysql

  selector:
    matchLabels:
      app: {{ .Release.Name }}-mysql

  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-mysql

    spec:
      containers:
      - name: mysql

        image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}"

        imagePullPolicy: {{ .Values.mysql.image.pullPolicy }}

        ports:
        - containerPort: 3306

        env:

        - name: MYSQL_DATABASE
          value: {{ .Values.mysql.database | quote }}

        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-mysql-secret
              key: WORDPRESS_DB_USER

        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-mysql-secret
              key: WORDPRESS_DB_PASSWORD

        - name: MYSQL_ROOT_PASSWORD
          value: {{ .Values.mysql.rootPassword | quote }}

        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql

  volumeClaimTemplates:

  - metadata:
      name: mysql-storage

    spec:

      accessModes:
      - ReadWriteOnce

      storageClassName: {{ .Values.mysql.storage.storageClass }}

      resources:
        requests:
          storage: {{ .Values.mysql.storage.size }}

