apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mysql-secret
type: Opaque
stringData:
  WORDPRESS_DB_USER: {{ .Values.mysql.user | quote }}
  WORDPRESS_DB_PASSWORD: {{ .Values.mysql.password | quote }}

